# Matrix Algebra using Python

Authors <a href="mailto:a.owen@leeds.ac.uk"> Dr Anne Owen </a> and <a href="mailto:j.busch@leeds.ac.uk"> Dr Jonathan Busch </a>

Before we start anything interesting, paste the two lines of code below into the box
to import the numpy library and to set some display settings. Remember to press Shift-Return to run the cell.

```python
import numpy as np
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'
```

In [2]:
import numpy as np
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'


# 1. Definitions and getting started

A <b>matrix</b> is a collection of numbers ordered by rows and columns. This is a convenient way to store lots of data. One example of such data could be the scores of several students (rows) on several exams (columns). We usually enclose the numbers in a matrix inside square brackets:

$$
\textbf{X}=
\begin{bmatrix} 
5 & 8 & 2 \\
1 & 0 & 7 
\end{bmatrix}
$$

## Exercise 1.1: Make a matrix (i)

Look at how we construct matrix $\textbf{X}$ in Jupyter:

```python
X = np.array([[5, 8, 2], [1, 0, 7]])
```

We are using the array function from the numpy library. Try pasting the command to create $\textbf{X}$ into the box below:

In [3]:
X = np.array([[5, 8, 2], [1, 0, 7]])

array([[5, 8, 2],
       [1, 0, 7]])

$\textbf{X}$ is now a variable that we can refer to and use later. Try changing the numbers in the code above and running the line of code to make a new version of $\textbf{X}$. When you have finished experimenting, change $\textbf{X}$ back to the original version.

## Exercise 1.2: Make a matrix (ii)

What do you need to type to create 

$$
\textbf{Y}=
\begin{bmatrix} 
3 & 1 \\
6 & 7 \\
2 & 3 
\end{bmatrix}
$$

Make $\textbf{Y}$ in the box below:

In [4]:
Y = np.array([[3,1], [6,7], [2,3]])

array([[3, 1],
       [6, 7],
       [2, 3]])

## Exercise 1.3 using 'size'
$\textbf{X}$ is a 2-by-3 matrix. It has two rows and 3 columns.

Use the np.size function to find out the dimensions of $\textbf{X}$ and $\textbf{Y}$. 

Try ```np.size(X,0)``` and ```np.size(X,1)```

In [5]:
np.size(X,1)

3

```np.size(X,0)``` gives you the dimensions in the vertical direction i.e. the matrix has 2 rows.

```np.size(X,1)``` gives you the dimensions in the horizontal direction i.e. the matrix has 3 columns.

## Exercise 1.4 Locating a matrix element

$$
\textbf{X}=
\begin{bmatrix} 
5 & 8 & 2 \\
1 & 0 & 7 
\end{bmatrix}
$$

The elements of a matrix are numnbered in the following way:

$$
\textbf{X}=
\begin{bmatrix} 
x_{00} & x_{01} & x_{02} \\
x_{10} & x_{11} & x_{12} 
\end{bmatrix}
$$

In python you can refer to a cell within a matrix using its row and column number. For example, ```X[0,1]``` returns the answer $8$ because it is the number in the first row and second column.

What command returns the answer $7$ from the matrix $\textbf{X}$?

In [6]:
X[1,2]

7

## Exercise 1.5 Matrix types and the 'diag' function

A <b>vector</b> is a special type of matrix that only has one row or one column. Below, $\textbf{a}$ is a row vector and $\textbf{b}$ is a column vector:

$$
\textbf{a}=
\begin{bmatrix} 
2 & 7 & 4 
\end{bmatrix}
$$

$$
\textbf{b}=
\begin{bmatrix} 
7 \\
2 \\
3
\end{bmatrix}
$$

A <b>scalar</b> is a matrix with a single row and a single column (just one number). 

By convention, scalars are italicised (e.g. $f$), vectors are lower case and bold (e.g. $\textbf{a}$) and matrixes are upper case and bold (e.g.$\textbf{X}$).

A <b>square matrix</b> has as many rows as it has columns. $\textbf{S}$ is an example of a 3 rows by 3 columns (or 3-by-3) square matrix:

$$
\textbf{S}=
\begin{bmatrix} 
4 & 5 & 2 \\
7 & 1 & 0 \\
2 & 9 & 15 
\end{bmatrix}
$$

The diagonal elements of a matrix are those where the column and row number are equal. The diagonal elements of $\textbf{S}$ are 4, 1, and 15.

In a <b>diagonal matrix</b> all the off-diagonal elements are 0.

To create the row vector $\textbf{a}$ below we use ```a = np.array([[2,7,4]])``` note that we use double square brackets.

In [7]:
a = np.array([[2,7,4]])

array([[2, 7, 4]])

Now make the column vector $\textbf{b}$

In [8]:
b = np.array([[7], [2], [3]])

array([[7],
       [2],
       [3]])

The function ```np.diagflat()``` can be used to turn vectors into diagonal matrices. Try it out

In [9]:
np.diagflat(a)

array([[2, 0, 0],
       [0, 7, 0],
       [0, 0, 4]])

## Exercise 1.6 The identity matrix

An <b>identity</b> matrix is a diagonal matrix containing only $1$s on the diagonal. Identity matrices are denotes as $\textbf{I}$

To create 
$\textbf{I}=
\begin{bmatrix} 
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 
\end{bmatrix}
$ in python we use the ```np.identity``` function

Try ```I = np.identity(3)```

In [10]:
I = np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Exercise 1.7 Matrices of zeros

To create 
$\textbf{D}=
\begin{bmatrix} 
0 & 0 & 0 \\
0 & 0 & 0 
\end{bmatrix}
$ in python we use the ```np.zeros``` function

Try ```D = np.zeros((2,3))```

In [11]:
D = np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

# 2. Matrix addition and subtraction

To add and subtract two matrices, they must have the same dimensions. Remember the size function tells you the dimensions of your matrix. To perform matrix addtion or subtraction, we add the individual elements of each matrix together. For $\textbf{R} = \textbf{S} + \textbf{T}$, then $r_{ij} = s_{ij}+t_{ij}$

## Exercise 2.1 Adding matrixes

Create $\textbf{S}$ and $\textbf{T}$ in python and find the result $\textbf{R}$

$$
\textbf{S}=
\begin{bmatrix} 
1 & 5 & 6 \\
3 & 6 & 0 
\end{bmatrix}
$$

$$
\textbf{T}=
\begin{bmatrix} 
8 & 2 & 3 \\
4 & 1 & 6 
\end{bmatrix}
$$

Create $\textbf{S}$

In [12]:
S = np.array([[1, 5, 6], [3, 6, 0]])

array([[1, 5, 6],
       [3, 6, 0]])

Create $\textbf{T}$

In [13]:
T = np.array([[8, 2, 3], [4, 1, 6]])

array([[8, 2, 3],
       [4, 1, 6]])

Find $\textbf{R} = \textbf{S} + \textbf{T}$

In [14]:
R = S + T

array([[9, 7, 9],
       [7, 7, 6]])

## Exercise 2.2 Subtracting matrices

Now try ```R-T```

What is the result?

In [15]:
R-T

array([[1, 5, 6],
       [3, 6, 0]])

# 3. Matrix multiplication

To multiply a matrix by a scalar, each element in the matrix is simply multiplied by the scalar. 

For $\textbf{Q} = a\textbf{S}$, then $q_{ij} = as_{ij}$

## Exercise 3.1 Pre-multiplication by a scalar

If $a=10$, what answer matrix do you think the following will give

```Q = a * S```

Check that you were right, by first telling python that ```a = 10```:

In [16]:
a=10

10

Now try ```Q = a * S```

In [17]:
Q = a * S

array([[10, 50, 60],
       [30, 60,  0]])

Matrix multiplication involving a scalar is commutative. That is $a\boldsymbol{S} = \boldsymbol{S}a$, so

```Q = S * a```

should give the same answer as above

In [18]:
Q = S * a

array([[10, 50, 60],
       [30, 60,  0]])

## Exercise 3.2 Pre- and post-multiplying by a scalar

What do you think the following code will give:

```Q = a * S * a```

Check that you were right:

In [19]:
Q = a * S * a

array([[100, 500, 600],
       [300, 600,   0]])

## Exercise 3.3 Multiplying two vectors together

To multiply a row vector by a column vector, the row vector must have the same number of columns as the column vector has rows.

In Python create the following vectors:

$$
\textbf{a}=
\begin{bmatrix} 
1 & 7 & 5 
\end{bmatrix}
$$

$$
\textbf{b}=
\begin{bmatrix} 
2 \\
4 \\
1
\end{bmatrix}
$$

$$
\textbf{c}=
\begin{bmatrix} 
2 \\
4 \\
1 \\
6 \\
2
\end{bmatrix}
$$

Make $\textbf{a}$

In [20]:
a = np.array([[1, 7, 5]])

array([[1, 7, 5]])

Make $\textbf{b}$

In [21]:
b = np.array([[2], [4], [1]])

array([[2],
       [4],
       [1]])

Make $\textbf{c}$

In [22]:
c = np.array([[2], [4], [1], [6], [2]])

array([[2],
       [4],
       [1],
       [6],
       [2]])

$\textbf{a}$ is a [$1$x$3$] row vector, $\textbf{b}$ is a [$3$x$1$] column vector and $\textbf{c}$ is a [$5$x$1$] column vector. For matrix multiplication, the 'inner' dimensions of the matrices you are multiplying must match.

To find out the result of $\textbf{ab}$ we use the code ```np.dot(a,b)```. 

```np.dot``` is the function for matrix multiplication.

In [23]:
np.dot(a, b)

array([[35]])

In this case we have [$1$x$3$] x [$3$x$1$]. The inner dimension $3$ matches.

What is the result of $\textbf{ac}$?

In [24]:
np.dot(a,c)

ValueError: shapes (1,3) and (5,1) not aligned: 3 (dim 1) != 5 (dim 0)

Why cant you calculate $\textbf{ac}$?

In this case [$1$x$3$] x [$5$x$1$]. The inner dimension does not match. $3$ is different to $5$

The product of a row vector multiplied by a column vector is a scalar (a single number). The scalar is the sum of the first row vector element multiplied by the first column vector element plus the second row vector element multiplied by the second column vector element, and so on. If ${r} = \textbf{ab}$, then

$$
r = \sum_{i=1}^n a_i b_i
$$

$$
\textbf{r}=
\begin{bmatrix} 
1 & 7 & 5 
\end{bmatrix}.
\begin{bmatrix} 
2 \\
4 \\
1 \\
\end{bmatrix}
=(1*2)+(7*4)+(5*1)=35
$$

## Exercise 3.4 Multiplying two matrices together

Remember, 

$$
\textbf{X}=
\begin{bmatrix} 
5 & 8 & 2 \\
1 & 0 & 7 
\end{bmatrix}
$$

and 

$$
\textbf{Y}=
\begin{bmatrix} 
3 & 1 \\
6 & 7 \\
2 & 3 
\end{bmatrix}
$$

Calculate $\textbf{P=XY}$ remember to use the ```np.dot``` function

In [25]:
P = np.dot(X, Y)

array([[67, 67],
       [17, 22]])

Note that: 

$$p_{00} = (5*3) + (8*6) + (2*2) = 67$$
$$p_{01} = (5*1) + (8*7) + (2*3) = 67$$
$$p_{10} = (1*3) + (0*6) + (7*2) = 17$$
$$p_{11} = (1*1) + (0*7) + (7*3) = 22$$

## Exercise 3.5 Checking if commutative

Is this calculation commutative? What is $\textbf{P=YX}$? Does this new $\textbf{P}$ have the dimensions you expected?

In [26]:
P = np.dot(Y, X)

array([[16, 24, 13],
       [37, 48, 61],
       [13, 16, 25]])

You should have found that matrix multiplication is not commutative and you get a different answer.

## Exercise 3.6 Multiplying by the identity matric

Calculate $\textbf{P=PI}$

In [27]:
P = np.dot(I, P)

array([[16., 24., 13.],
       [37., 48., 61.],
       [13., 16., 25.]])

Note that the identity matrix acts like 1. Pre-multiplying or post-multiplying by the identity matrix has no effect.

# 4. Matrix transpose

Transposing a matrix swaps the rows to be columns, or turns a row vector into a column vector (or vice-versa). In algebra this is denoted by the apostrophe:  $\textbf{P'}$ is the transpose of $\textbf P$.

## Exercise 4.1 Using transpose in python

In python try ```np.transpose(P)```

In [28]:
np.transpose(P)

array([[16., 37., 13.],
       [24., 48., 16.],
       [13., 61., 25.]])

# 5. Matrix inverse

The inverse of a number is the number which, when multiplied by the original number, gives a product of 1. Hence the inverse of $4$ is $\frac{1}{4}$, because $4 * \frac{1}{4} = 1$. The inverse of $x$ is $\frac{1}{x}$ or $x^{-1}$.

In matrix algebra, the inverse of a matrix is that matrix which, when multiplied by the original matrix, gives the identity matrix, so: $${\textbf{A}\textbf{A}^{-1} = \textbf{I}}$$

## Exercise 5.1 Inverting a matrix in Python

Make 

$$
\textbf{X}=
\begin{bmatrix} 
2 & 0 & 1\\
3 & 1 & 1\\
4 & 2 & 3 
\end{bmatrix}
$$

In [29]:
X = np.array([[2,0,1],[3,1,1],[4,2,3]])

array([[2, 0, 1],
       [3, 1, 1],
       [4, 2, 3]])

And use the ```np.linalg.inv()``` function to find $\textbf{X}^{-1}$

You can call this variable ```invX``` if you like

In [30]:
invX = np.linalg.inv(X)

array([[ 0.25,  0.5 , -0.25],
       [-1.25,  0.5 ,  0.25],
       [ 0.5 , -1.  ,  0.5 ]])

## Exercise 5.2 Multiplying a matrix by its inverse

What is the result of $\textbf{X}\textbf{X}^{-1}$

In [31]:
np.dot(X, invX)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 6. Element-wise multiplication and division

Another type of matrix product is the element-wise product. In this case, each $i$, $j$ element of $\textbf{A}$ is multiplied with each $i$, $j$ element of $\textbf{B}$. In other words, the element in the first row, first column of $\textbf{A}$ is multiplied with the element in the same position of $\textbf{B}$ to form the element in the new result matrix. 

This is <b>different</b> to the matrix multiplication discussed in section 3. In matrix algbra, this element-wise multiplication is written as $\textbf{A} \circ \textbf{B}$ and is called the Hadamard product.

## Exercise 6.1 Element-wise multiplication of matrices

In Python create

$$
\textbf{Y}=
\begin{bmatrix} 
5 & 1 & 0\\
1 & 3 & 7\\
4 & 2 & 3 
\end{bmatrix}
$$

In [33]:
Y = np.array([[5,1,0],[1,3,7],[4,2,3]])

array([[5, 1, 0],
       [1, 3, 7],
       [4, 2, 3]])

Use ```np.multiply(X,Y)``` to find $\textbf{X} \circ \textbf{Y}$

In [34]:
np.multiply(X,Y)

array([[10,  0,  0],
       [ 3,  3,  7],
       [16,  4,  9]])

Now try ```X * Y```

In [35]:
X * Y

array([[10,  0,  0],
       [ 3,  3,  7],
       [16,  4,  9]])

Does this simple multiplication give true matrix multiplication or the Hadamard product?

Be very careful that you chose the correct type of matrix multiplication function in our work with matrices. Most of the time we will be working with ```np.dot()```

## Exercise 6.2 Element-wise division of matrices

Try ```np.divide(X,Y)``` and try ```X/Y```

In [36]:
X/Y

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.4       , 0.        ,        inf],
       [3.        , 0.33333333, 0.14285714],
       [1.        , 1.        , 1.        ]])

Note that we are having a problem dividing 1 by zero, leaving an infinity in the top right cell.

We'll talk about how to deal with this in a later tutorial.

# 7. Further matrix operations in Python

## Exercise 7.1 Sums

What do the following commands do ```np.sum(X,0)```, ```np.sum(X,1)``` and ```np.sum(np.sum(X))```?

In [41]:
np.sum(np.sum(X))

17

In python matrices we refer to cells by giving the the row location followed by the column location. Think of this as "how many down, then how many across". In the ```np.sum``` function, the specifier ```0``` has the effect of summing 'down' and the specifier ```1``` has the effect of summing 'across'. ```np.sum(np.sum))``` has the effect of summing in both dimensions to give the total of the whole matrix

## Exercise 7.2 Extracting a single row from a matrix

To select the first row of $\textbf{X}$ we use the command ```X[0,:]``` This means take the first row and every column element. What do you get if you use the command ```X[:,1]```?

In [42]:
X[:,1]

array([0, 1, 2])

## Exercise 7.3 Extracting a single column from a matrix

Can you write a single command to find the sum of the 3rd column of $\textbf{X}$

In [43]:
np.sum(X[:,2])

5

## Exercise 7.4 Repeated rows

Find ```t = np.sum(X,0)```

In [44]:
t = np.sum(X, 0)

array([9, 3, 5])

If we wanted to find the proportion that each element in $\textbf{X}$ was of the total column sum, we’d want to divide each element in $\textbf{X}$ by the corresponding column sum in $\textbf{t}$. But to use element-wise division, the dimensions of each matrix must be the same. In this case $(3,3)$. What we need to do is make a new matrix $\textbf{T}$, which has 3 rows each containing the original $\textbf{t}$ and use this in our division calculation. The command:

```python
T = np.tile(t,[3,1])
```

makes a new matrix $\textbf{T}$ by repeating original $\textbf{t}$ down three rows but does not repeat across any more columns. <b>We will be using this concept in workbook 2</b>. Try it!

In [45]:
T = np.tile(t,[3,1])

array([[9, 3, 5],
       [9, 3, 5],
       [9, 3, 5]])

Now we can divide $\textbf{X}$ by  $\textbf{T}$ to give a new matrix showing what proportion each element is of the column total. <b>We will be using this concept in workbook 2</b>. Yes I've said this twice. Try 

```prop = X/T```

In [46]:
prop = X/T

array([[0.22222222, 0.        , 0.2       ],
       [0.33333333, 0.33333333, 0.2       ],
       [0.44444444, 0.66666667, 0.6       ]])

## Key learning points

You should have learnt:

<ol>
<li>What matrices, vectors and scalars are</li>
<li>How to make matrices in Python using the np.array function</li>
<li>What the conditions are for adding and subtracting matrices</li>
<li>What the two types of matrix multiplication are</li>
<li>What the conditions are for matrix multiplication</li>
<li>What the inverse of a matrix means</li>
<li>What the identity matrix is and how it works</li>
<li>How to make diagonal matrices and matrices of zeros</li>
<li>How to refer to matrix rows, columns and individual elements</li>
<li>How to sum matrices along the rows and along the columns</li>
<li>How the tile function works</li>
   
</ol>
